apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: gateway-default
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: gateway-default
spec:
  params:
    - name: annotations
      value:
        autoscaling.knative.dev/minScale: 1
  source:
    git:
      url: https://github.com/doing-more-with-less-and-tce/gateway
      ref:
        branch: main